language: node_js
node_js:
  - "6"
script:
  - npm run lint
  - npm run build
before_deploy:
  - npm version patch
  - git config user.email ${GIT_EMAIL}
  - git config user.name ${GIT_USERID}
  - git add package.json
  - git commit -m "Updated version"
  - git push "https://${GIT_TOKEN}@github.com/${GIT_USERID}/react-ui-suit.git" master
deploy:
  provider: npm
  skip_cleanup: true
  email: $EMAIL_ADDRESS
  api_key: $NPM_TOKEN
  on:
    branch: master
